config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    root to: "static_pages#home"
  end

  get '/choose_subject', to: "static_pages#choose_subject"
  resources :course_memberships, only: [:create]
  resources :courses, only: [:show]
  resources :notes, only: [:show, :create]
  resources :mock_exams, only: [:new, :create, :show] do
    post 'submit', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :notes
  has_many :mcq_questions
  has_many :flashcards

  has_many :course_memberships
  has_many :users, through: :course_memberships

  has_many :fill_in_questions
end

app/models/course_membership.rb
class CourseMembership < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/exam_mcq_relationship.rb
class ExamMcqRelationship < ApplicationRecord
  belongs_to :mock_exam
  belongs_to :mcq_question
end

app/models/fill_in_question.rb
class FillInQuestion < ApplicationRecord
  belongs_to :course
end

app/models/flashcard.rb
class Flashcard < ApplicationRecord
  belongs_to :course
end

app/models/mcq_question.rb
class McqQuestion < ApplicationRecord
  belongs_to :course
end

app/models/mock_exam.rb
class MockExam < ApplicationRecord
  belongs_to :user
  belongs_to :course

  has_many :exam_mcq_relationships
  has_many :mcq_questions, through: :exam_mcq_relationships

  has_many :exam_fill_in_question_relationships
  has_many :exam_fill_in_questions, through: :exam_fill_in_question_relationships, source: :fill_in_question
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes
  has_many :course_memberships
  has_many :courses, through: :course_memberships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/course_memberships_controller.rb
class CourseMembershipsController < ApplicationController
  before_action :authenticate_user!

  def create
    puts params
    course = Course.find_by(course_id: params[:course_membership][:course_id])
    if course.nil?
      flash[:notice] = "Course does not exist"
      render "static_pages/home"
    else
      membership = CourseMembership.create(course: course, user: current_user)
      redirect_to course
    end
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/mock_exams_controller.rb
class MockExamsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def show
    @mock_exam = MockExam.find(params[:id])
  end

  def create
    @mock_exam = MockExam.create(name: params[:mock_exam][:name], course_id: "1", user_id: current_user.id)

    # grab the questions
    @questions = @mock_exam.course.fill_in_questions

    @questions.each do |question|
      if rand() > 0.5
        @mock_exam.exam_fill_in_questions << question
      end
    end

    # redirect to the exam
    redirect_to @mock_exam
  end

  def submit
    @mock_exam = MockExam.find(params[:id])
    puts params
    answers = params[:anything]
    
    num_question = 0
    num_correct_answer = 0

    puts "YOOOOOOOOOO"
    puts answers

    answers.each do |key, value|
      correct_answer = FillInQuestion.find(key).answer
      num_question += 1
      rela = ExamFillInQuestionRelationship.find_by(mock_exam_id: @mock_exam.id, fill_in_question_id: key)
      rela.update_attributes(answer: value)
      if correct_answer == value
        rela.update_attributes(correct: true)
        num_correct_answer += 1
      else
        rela.update_attributes(correct: false)
      end
    end

    @mock_exam.update_attributes(score: num_correct_answer, num_questions: num_question)
    render "mock_exams/result"
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  require "uri"
  require "net/http"

  before_action :authenticate_user!

  def show
    @note = Note.find(params[:id])
  end

  def create
    @course = params[:note][:course_id]
    note = Note.new(body: params[:note][:body], course_id: params[:note][:course_id], user_id: current_user.id)
    if note.save
      redirect_to note
    else
      flash[:danger] = "Can't save!"
      render @course
    end


    uri = URI('https://1jwjnlh7r4.execute-api.us-east-2.amazonaws.com/prod/text2test')
    req = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json')
    req.body = {inputTranscript: note.body}.to_json

    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    res = http.request(req)

    puts "RESPONSE!!!!!!!!!!!!"
    parsed_res = ActiveSupport::JSON.decode(res.body)

    parsed_res["body"].each do |question|
      fill_in = FillInQuestion.create(question: question["question"], answer: question["answer"], course_id: 1)
      puts "#{fill_in.question}:#{fill_in.answer}"
    end


  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!
  
  def home
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def choose_subject

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_memberships_helper.rb
module CourseMembershipsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/mock_exams_helper.rb
module MockExamsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/courses/_course_block.html.erb
<%= link_to course do %>
  <div class="course-block">
    <% if course.topic == "Anthropology" %>
      <%= image_tag 'Artboard 1 copy 2.png', class: "course-image #{course.topic}" %>
    <% elsif course.topic == "Maths" %>
      <%= image_tag 'Artboard 1 copy.png', class: "course-image #{course.topic}" %>

    <% end %>
    <%= content_tag :p, course.course_id, class: "course-title #{course.topic}" %>

  </div>
<% end %>

<style>
<% if course.topic == "Anthropology" %>
.course-image.Anthropology {
  background-color: #066f6e;
}

.course-title.Anthropology {
  color: #066f6e;
}
<% else %>
.course-image.Maths {
  background-color: #bd1d1d;
}

.course-title.Maths {
  color: #bd1d1d;
}
<% end %>
</style>

app/views/courses/show.html.erb
<div class="login-container">
  <h2> Copy and Paste your notes in the box </h2>
  <%= form_for Note.new do |f| %>
    <%= f.hidden_field :course_id, value: @course.id %>
    <div class="field note-block">
      <%= f.text_area :body, autofocus: true, autocomplete: "note", class: "note-input" %>
    </div>
    <div class="note-actions">
      <%= link_to "Cancel", "/choose_subject", class: "btn cancel", style: "background-color: #d8d8d8; width: 240px; height: 50px;" %>
      <%= f.submit "Upload", class: "btn", style: "width: 240px; height: 50px;" %>
    </div>
  <% end %>
</div>

app/views/static_pages/choose_subject.html.erb
<div class="login-container">
  <h2> Choose your following courses </h2>
  <div class="subject-block">
    <% current_user.courses.each do |course| %>
      <%= render partial: "courses/course_block", locals: {course: course} %>
    <% end %>
  </div>
</div>

app/views/static_pages/home.html.erb
<p>
  <%= current_user.name.nil? ? "Hello!" : "Hello, #{current_user.name}!" %>
</p>

<%= form_for CourseMembership.new do |f| %>
  <div class="field">
    <%= f.label :course_id %><br />
    <%= f.text_field :course_id, autofocus: true, autocomplete: "course_id" %>
  </div>
  <div class="actions">
    <%= f.submit "Join course", class: "btn", style: "height: 50px; width: 150px;" %>
  </div>
<% end %>

<h2> Current courses </h2>
<% current_user.courses.each do |course| %>
  <%= render partial: "courses/course_block", locals: {course: course} %>
<% end %>

<%= link_to "Take an Exam!", new_mock_exam_path, class: "btn cancel", style: "display: block; height: 50px; width: 150px; margin-top: 20px;" %>

<p>
  <%= link_to "Logged out", destroy_user_session_path, method: :delete %> <br />
</p>